/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dolores (https://sketchfab.com/upto21)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/microscope-9f5942f7c92d49b8a608903c556de37d
title: Microscope
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/1/scene.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]} scale={0.53}>
//         <group position={[0.53, 1.92, 0.9]} rotation={[0, 0, -Math.PI]} scale={[1.66, 1.42, 0.15]}>
//           <mesh geometry={nodes.Cube002_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[-0.09, 1.63, 1.17]} rotation={[Math.PI / 2, 0, 0]} scale={[0.14, 0.14, 0.07]}>
//           <mesh geometry={nodes.Cylinder_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[-0.09, 2.03, 1.17]} rotation={[Math.PI / 2, 0, 0]} scale={[0.14, 0.14, 0.07]}>
//           <mesh geometry={nodes.Cylinder001_0.geometry} material={materials.Root} />
//         </group>
//         <group position={[-0.09, 2.22, 1.17]} rotation={[Math.PI / 2, 0, 0]} scale={[0.14, 0.14, 0.07]}>
//           <mesh geometry={nodes.Cylinder002_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[1.2, 1.94, 1.76]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-1.08, 1.06, 0.06]}>
//           <mesh geometry={nodes.Cube006_0.geometry} material={materials['Material.003']} />
//         </group>
//         <group position={[0.91, 1.93, 3.39]} scale={[0.33, 0.33, 0.61]}>
//           <mesh geometry={nodes.Cylinder003_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.91, 1.93, 4.05]} scale={[0.35, 0.35, 0.05]}>
//           <mesh geometry={nodes.Cylinder004_0.geometry} material={materials.black} />
//         </group>
//         <group position={[0.11, 1.71, 2.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.22, 0.22, 0.04]}>
//           <mesh geometry={nodes.Cylinder005_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.12, 1.59, 2.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.17, 0.17, 0.16]}>
//           <mesh geometry={nodes.Cylinder006_0.geometry} material={materials.metal} />
//           <mesh geometry={nodes.Cylinder006_1.geometry} material={materials.dark_plastic} />
//         </group>
//         <group position={[0.45, 1.61, 3.75]} rotation={[Math.PI / 2, 0, 0]} scale={[0.22, 0.22, 0.04]}>
//           <mesh geometry={nodes.Cylinder008_0.geometry} material={materials.metal} />
//           <mesh geometry={nodes.Cylinder008_1.geometry} material={materials.dark_plastic} />
//         </group>
//         <group position={[0.51, 1.93, 3.39]} scale={[0.17, 0.18, 0.61]}>
//           <mesh geometry={nodes.Cube004_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.45, 2.25, 3.75]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.22, 0.22, 0.04]}>
//           <mesh geometry={nodes.Cylinder007_0.geometry} material={materials.metal} />
//           <mesh geometry={nodes.Cylinder007_1.geometry} material={materials.dark_plastic} />
//         </group>
//         <group position={[0.12, 2.26, 2.91]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[0.17, 0.17, 0.16]}>
//           <mesh geometry={nodes.Cylinder009_0.geometry} material={materials.metal} />
//           <mesh geometry={nodes.Cylinder009_1.geometry} material={materials.dark_plastic} />
//         </group>
//         <group position={[0.11, 2.13, 2.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.22, 0.22, 0.04]}>
//           <mesh geometry={nodes.Cylinder010_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.45, 1.93, 3.73]} rotation={[Math.PI / 2, 0, 0]} scale={[0.06, 0.06, 0.35]}>
//           <mesh geometry={nodes.Cylinder011_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.21, 1.93, 1.19]} rotation={[0, 0, -Math.PI]} scale={[0.14, 0.18, 0.5]}>
//           <mesh geometry={nodes.Cube005_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.92, 1.93, 2.68]} scale={[0.23, 0.23, 0.05]}>
//           <mesh geometry={nodes.Cylinder012_0.geometry} material={materials.black} />
//         </group>
//         <group position={[0.92, 1.93, 2.79]} scale={[0.23, 0.23, 0.06]}>
//           <mesh geometry={nodes.Cylinder013_0.geometry} material={materials.dark_plastic} />
//         </group>
//         <group position={[1.17, 1.93, 2.66]} rotation={[0, -0.18, 0]} scale={[0.57, 0.57, 0.05]}>
//           <mesh geometry={nodes.Cylinder014_0.geometry} material={materials.black} />
//         </group>
//         <group position={[1.17, 1.93, 2.63]} rotation={[-Math.PI, 0.18, 0]} scale={[0.56, 0.56, 0.05]}>
//           <mesh geometry={nodes.Cylinder015_0.geometry} material={materials.dark_plastic} />
//         </group>
//         <group position={[0.45, 1.93, 0.73]} rotation={[0, Math.PI / 2, 0]} scale={[0.02, 0.02, 0.15]}>
//           <mesh geometry={nodes.Cylinder016_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.94, 1.91, 0.73]} scale={[0.39, 0.39, 0.06]}>
//           <mesh geometry={nodes.Cylinder017_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.96, 1.91, 0.72]} rotation={[0, 0.48, 0]} scale={[0.36, 0.36, 0.05]}>
//           <mesh geometry={nodes.Cylinder018_0.geometry} material={materials.black} />
//         </group>
//         <group position={[0.96, 1.91, 0.72]} rotation={[0, 0.48, 0]} scale={[0.36, 0.36, 0.05]}>
//           <mesh geometry={nodes.Cylinder019_0.geometry} material={materials['mirror.001']} />
//         </group>
//         <group position={[0.94, 1.93, 2.25]} rotation={[-Math.PI, 0, 0]} scale={[0.16, 0.16, 0.19]}>
//           <mesh geometry={nodes.Cylinder020_0.geometry} material={materials.grey} />
//         </group>
//         <group position={[0.94, 1.93, 2.42]} scale={[0.17, 0.17, 0.05]}>
//           <mesh geometry={nodes.Cylinder021_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.94, 1.93, 2]} scale={[0.12, 0.12, 0.02]}>
//           <mesh geometry={nodes.Cylinder022_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[1.39, 1.51, 2.04]} rotation={[-0.27, -0.21, -0.06]} scale={[0.12, 0.12, 0.02]}>
//           <mesh geometry={nodes.Cylinder023_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[1.29, 1.64, 2.49]} rotation={[-0.27, -0.21, -0.06]} scale={[0.17, 0.17, 0.05]}>
//           <mesh geometry={nodes.Cylinder024_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[1.34, 1.58, 2.28]} rotation={[2.87, 0.21, 0.06]} scale={[0.16, 0.16, 0.19]}>
//           <mesh geometry={nodes.Cylinder025_0.geometry} material={materials.grey} />
//         </group>
//         <group position={[1.53, 2.18, 2.29]} rotation={[-2.96, 0.39, -0.11]} scale={[0.16, 0.16, 0.19]}>
//           <mesh geometry={nodes.Cylinder026_0.geometry} material={materials.grey} />
//         </group>
//         <group position={[1.43, 2.14, 2.53]} rotation={[0.18, -0.39, 0.11]} scale={[0.17, 0.17, 0.05]}>
//           <mesh geometry={nodes.Cylinder027_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[1.63, 2.22, 2.06]} rotation={[0.18, -0.39, 0.11]} scale={[0.12, 0.12, 0.02]}>
//           <mesh geometry={nodes.Cylinder028_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.24, 1.22, 1.87]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.03}>
//           <mesh geometry={nodes.Cylinder029_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.24, 1.22, 1.92]} scale={[-0.06, 0.06, 0.03]}>
//           <mesh geometry={nodes.Cylinder030_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.24, 2.64, 1.92]} scale={[-0.06, 0.06, 0.03]}>
//           <mesh geometry={nodes.Cylinder031_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.24, 2.64, 1.87]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.03}>
//           <mesh geometry={nodes.Cylinder032_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[1.01, 1.91, 1.66]} scale={[0.36, 0.36, 0.04]}>
//           <mesh geometry={nodes.Cylinder033_0.geometry} material={materials.black} />
//         </group>
//         <group position={[1.01, 1.91, 1.59]} scale={[0.4, 0.4, 0.05]}>
//           <mesh geometry={nodes.Cylinder034_0.geometry} material={materials.black} />
//         </group>
//         <group position={[1.01, 1.91, 1.51]} scale={[0.35, 0.35, 0.04]}>
//           <mesh geometry={nodes.Cylinder035_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[1.01, 1.91, 1.47]} scale={[0.39, 0.39, 0.05]}>
//           <mesh geometry={nodes.Cylinder036_0.geometry} material={materials.black} />
//         </group>
//         <group position={[0.93, 1.21, 1.95]} scale={[0.62, 0.05, 0.46]}>
//           <mesh geometry={nodes.Plane_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.93, 2.62, 1.95]} scale={[0.62, 0.05, 0.46]}>
//           <mesh geometry={nodes.Plane001_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.9, 1.93, 4.13]} scale={[0.25, 0.25, 0.04]}>
//           <mesh geometry={nodes.Cylinder037_0.geometry} material={materials.black} />
//         </group>
//         <group position={[0.9, 1.93, 4.6]} scale={[0.23, 0.23, 0.43]}>
//           <mesh geometry={nodes.Cylinder038_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.91, 1.93, 5.04]} scale={[0.27, 0.27, 0.18]}>
//           <mesh geometry={nodes.Cylinder039_0.geometry} material={materials.black} />
//         </group>
//         <group position={[0.26, 1.41, 1.36]} rotation={[Math.PI / 2, 0, 0]} scale={[0.17, 0.17, 0.16]}>
//           <mesh geometry={nodes.Cylinder040_0.geometry} material={materials.metal} />
//           <mesh geometry={nodes.Cylinder040_1.geometry} material={materials.dark_plastic} />
//         </group>
//         <group position={[0.23, 1.65, 1.36]} rotation={[Math.PI / 2, 0, 0]} scale={[0.04, 0.04, 0.22]}>
//           <mesh geometry={nodes.Cylinder041_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[0.93, 2.24, 3.21]} rotation={[-Math.PI / 2, 0, 0]} scale={0.58}>
//           <mesh geometry={nodes.Plane003_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[-0.32, 1.17, 0.25]} scale={0.53}>
//           <mesh geometry={nodes.Plane004_0.geometry} material={materials.metal} />
//         </group>
//         <group position={[-0.32, 1.56, 0.25]} scale={0.53}>
//           <mesh geometry={nodes.Plane005_0.geometry} material={materials.metal} />
//         </group>
//       </group>
//     </group>
//   )
// }

export default function Model() {
  const gltf = useGLTF('/1/scene.gltf')
  return (<primitive object={gltf.scene} />)
}

useGLTF.preload('/1/scene.gltf')
